import type { Metadata } from "next";
import "./globals.css";
import { archivoSans, googleSans } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivoSans.className}`}>{children}</body>
    </html>
  );
}
